import {React, useState} from 'react';
import Modal from '../components/Modal';
import Button from '../components/Buttons';

const ModalPage = () => {
    const [showModal, setShowModal] = useState(false);

    const handleClick = () => {
        setShowModal(true);
    }

    const handleClose = () => {
        setShowModal(false);
    }
    const buttonAccept = (
        <Button success>
            Accept
        </Button>
    )
    const modal = (
        <Modal handleClose={handleClose} actionBar={buttonAccept}>
            Here are some informations for user to agree and follow:
        </Modal>
    )
    return (
        <div>
            <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac porta ipsum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec scelerisque fermentum placerat. Nulla facilisi. Donec id lorem ac erat mollis sollicitudin. Aliquam molestie egestas tellus, eget facilisis lectus iaculis a. Nulla at sapien id magna scelerisque consequat. Pellentesque egestas tellus mi, in tempor eros convallis non. Suspendisse potenti. Praesent ac massa ut libero tempus lobortis sit amet ut tellus. Mauris accumsan purus in sodales finibus. Aliquam elementum rutrum ipsum, quis hendrerit libero euismod et. Nullam lorem dui, consequat id vulputate a, aliquam in elit. Ut commodo suscipit dapibus.Mauris tempor aliquam magna ac luctus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Suspendisse dapibus lorem ut quam gravida mollis. Duis a mi tempus, suscipit metus ac, efficitur purus. In nibh ipsum, imperdiet non semper vel, commodo id velit. In sed ultrices erat. Praesent varius, lorem ac ultricies bibendum, sem tellus tristique leo, a dignissim nibh ligula eu felis. Mauris pulvinar molestie enim, quis pharetra odio ullamcorper eget. Donec dictum vitae massa ac commodo. Quisque fermentum, sapien eu posuere blandit, nunc libero gravida erat, at dictum tortor quam id mauris. Mauris in est orci. Proin eu maximus ligula. Nulla placerat dolor luctus erat cursus fermentum. Nam porttitor ultrices augue a iaculis. Nam vulputate neque a tempor semper. Nullam pellentesque euismod fringilla.
            </p>
            <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac porta ipsum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec scelerisque fermentum placerat. Nulla facilisi. Donec id lorem ac erat mollis sollicitudin. Aliquam molestie egestas tellus, eget facilisis lectus iaculis a. Nulla at sapien id magna scelerisque consequat. Pellentesque egestas tellus mi, in tempor eros convallis non. Suspendisse potenti. Praesent ac massa ut libero tempus lobortis sit amet ut tellus. Mauris accumsan purus in sodales finibus. Aliquam elementum rutrum ipsum, quis hendrerit libero euismod et. Nullam lorem dui, consequat id vulputate a, aliquam in elit. Ut commodo suscipit dapibus.Mauris tempor aliquam magna ac luctus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Suspendisse dapibus lorem ut quam gravida mollis. Duis a mi tempus, suscipit metus ac, efficitur purus. In nibh ipsum, imperdiet non semper vel, commodo id velit. In sed ultrices erat. Praesent varius, lorem ac ultricies bibendum, sem tellus tristique leo, a dignissim nibh ligula eu felis. Mauris pulvinar molestie enim, quis pharetra odio ullamcorper eget. Donec dictum vitae massa ac commodo. Quisque fermentum, sapien eu posuere blandit, nunc libero gravida erat, at dictum tortor quam id mauris. Mauris in est orci. Proin eu maximus ligula. Nulla placerat dolor luctus erat cursus fermentum. Nam porttitor ultrices augue a iaculis. Nam vulputate neque a tempor semper. Nullam pellentesque euismod fringilla.
            </p>
            <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac porta ipsum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec scelerisque fermentum placerat. Nulla facilisi. Donec id lorem ac erat mollis sollicitudin. Aliquam molestie egestas tellus, eget facilisis lectus iaculis a. Nulla at sapien id magna scelerisque consequat. Pellentesque egestas tellus mi, in tempor eros convallis non. Suspendisse potenti. Praesent ac massa ut libero tempus lobortis sit amet ut tellus. Mauris accumsan purus in sodales finibus. Aliquam elementum rutrum ipsum, quis hendrerit libero euismod et. Nullam lorem dui, consequat id vulputate a, aliquam in elit. Ut commodo suscipit dapibus.Mauris tempor aliquam magna ac luctus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Suspendisse dapibus lorem ut quam gravida mollis. Duis a mi tempus, suscipit metus ac, efficitur purus. In nibh ipsum, imperdiet non semper vel, commodo id velit. In sed ultrices erat. Praesent varius, lorem ac ultricies bibendum, sem tellus tristique leo, a dignissim nibh ligula eu felis. Mauris pulvinar molestie enim, quis pharetra odio ullamcorper eget. Donec dictum vitae massa ac commodo. Quisque fermentum, sapien eu posuere blandit, nunc libero gravida erat, at dictum tortor quam id mauris. Mauris in est orci. Proin eu maximus ligula. Nulla placerat dolor luctus erat cursus fermentum. Nam porttitor ultrices augue a iaculis. Nam vulputate neque a tempor semper. Nullam pellentesque euismod fringilla.
            </p>
            <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac porta ipsum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec scelerisque fermentum placerat. Nulla facilisi. Donec id lorem ac erat mollis sollicitudin. Aliquam molestie egestas tellus, eget facilisis lectus iaculis a. Nulla at sapien id magna scelerisque consequat. Pellentesque egestas tellus mi, in tempor eros convallis non. Suspendisse potenti. Praesent ac massa ut libero tempus lobortis sit amet ut tellus. Mauris accumsan purus in sodales finibus. Aliquam elementum rutrum ipsum, quis hendrerit libero euismod et. Nullam lorem dui, consequat id vulputate a, aliquam in elit. Ut commodo suscipit dapibus.Mauris tempor aliquam magna ac luctus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Suspendisse dapibus lorem ut quam gravida mollis. Duis a mi tempus, suscipit metus ac, efficitur purus. In nibh ipsum, imperdiet non semper vel, commodo id velit. In sed ultrices erat. Praesent varius, lorem ac ultricies bibendum, sem tellus tristique leo, a dignissim nibh ligula eu felis. Mauris pulvinar molestie enim, quis pharetra odio ullamcorper eget. Donec dictum vitae massa ac commodo. Quisque fermentum, sapien eu posuere blandit, nunc libero gravida erat, at dictum tortor quam id mauris. Mauris in est orci. Proin eu maximus ligula. Nulla placerat dolor luctus erat cursus fermentum. Nam porttitor ultrices augue a iaculis. Nam vulputate neque a tempor semper. Nullam pellentesque euismod fringilla.
            </p>
            <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac porta ipsum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec scelerisque fermentum placerat. Nulla facilisi. Donec id lorem ac erat mollis sollicitudin. Aliquam molestie egestas tellus, eget facilisis lectus iaculis a. Nulla at sapien id magna scelerisque consequat. Pellentesque egestas tellus mi, in tempor eros convallis non. Suspendisse potenti. Praesent ac massa ut libero tempus lobortis sit amet ut tellus. Mauris accumsan purus in sodales finibus. Aliquam elementum rutrum ipsum, quis hendrerit libero euismod et. Nullam lorem dui, consequat id vulputate a, aliquam in elit. Ut commodo suscipit dapibus.Mauris tempor aliquam magna ac luctus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Suspendisse dapibus lorem ut quam gravida mollis. Duis a mi tempus, suscipit metus ac, efficitur purus. In nibh ipsum, imperdiet non semper vel, commodo id velit. In sed ultrices erat. Praesent varius, lorem ac ultricies bibendum, sem tellus tristique leo, a dignissim nibh ligula eu felis. Mauris pulvinar molestie enim, quis pharetra odio ullamcorper eget. Donec dictum vitae massa ac commodo. Quisque fermentum, sapien eu posuere blandit, nunc libero gravida erat, at dictum tortor quam id mauris. Mauris in est orci. Proin eu maximus ligula. Nulla placerat dolor luctus erat cursus fermentum. Nam porttitor ultrices augue a iaculis. Nam vulputate neque a tempor semper. Nullam pellentesque euismod fringilla.
            </p>
            <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac porta ipsum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec scelerisque fermentum placerat. Nulla facilisi. Donec id lorem ac erat mollis sollicitudin. Aliquam molestie egestas tellus, eget facilisis lectus iaculis a. Nulla at sapien id magna scelerisque consequat. Pellentesque egestas tellus mi, in tempor eros convallis non. Suspendisse potenti. Praesent ac massa ut libero tempus lobortis sit amet ut tellus. Mauris accumsan purus in sodales finibus. Aliquam elementum rutrum ipsum, quis hendrerit libero euismod et. Nullam lorem dui, consequat id vulputate a, aliquam in elit. Ut commodo suscipit dapibus.Mauris tempor aliquam magna ac luctus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Suspendisse dapibus lorem ut quam gravida mollis. Duis a mi tempus, suscipit metus ac, efficitur purus. In nibh ipsum, imperdiet non semper vel, commodo id velit. In sed ultrices erat. Praesent varius, lorem ac ultricies bibendum, sem tellus tristique leo, a dignissim nibh ligula eu felis. Mauris pulvinar molestie enim, quis pharetra odio ullamcorper eget. Donec dictum vitae massa ac commodo. Quisque fermentum, sapien eu posuere blandit, nunc libero gravida erat, at dictum tortor quam id mauris. Mauris in est orci. Proin eu maximus ligula. Nulla placerat dolor luctus erat cursus fermentum. Nam porttitor ultrices augue a iaculis. Nam vulputate neque a tempor semper. Nullam pellentesque euismod fringilla.
            </p>
            <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac porta ipsum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec scelerisque fermentum placerat. Nulla facilisi. Donec id lorem ac erat mollis sollicitudin. Aliquam molestie egestas tellus, eget facilisis lectus iaculis a. Nulla at sapien id magna scelerisque consequat. Pellentesque egestas tellus mi, in tempor eros convallis non. Suspendisse potenti. Praesent ac massa ut libero tempus lobortis sit amet ut tellus. Mauris accumsan purus in sodales finibus. Aliquam elementum rutrum ipsum, quis hendrerit libero euismod et. Nullam lorem dui, consequat id vulputate a, aliquam in elit. Ut commodo suscipit dapibus.Mauris tempor aliquam magna ac luctus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Suspendisse dapibus lorem ut quam gravida mollis. Duis a mi tempus, suscipit metus ac, efficitur purus. In nibh ipsum, imperdiet non semper vel, commodo id velit. In sed ultrices erat. Praesent varius, lorem ac ultricies bibendum, sem tellus tristique leo, a dignissim nibh ligula eu felis. Mauris pulvinar molestie enim, quis pharetra odio ullamcorper eget. Donec dictum vitae massa ac commodo. Quisque fermentum, sapien eu posuere blandit, nunc libero gravida erat, at dictum tortor quam id mauris. Mauris in est orci. Proin eu maximus ligula. Nulla placerat dolor luctus erat cursus fermentum. Nam porttitor ultrices augue a iaculis. Nam vulputate neque a tempor semper. Nullam pellentesque euismod fringilla.
            </p>
            <Button success onClick={handleClick}>Open Modal</Button>
            {showModal && modal}
        </div>
    )
}

export default ModalPage